<a href="https://colab.research.google.com/github/AlishDuwal10/Worksheet/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# 1. Create an empty 2x2 array
a = np.empty((2, 2))
print("Empty 2x2 array:\n", a)

# 2. Create a 4x2 array of ones
b = np.ones((4, 2))
print("\nAll ones 4x2 array:\n", b)

# 3. Create a 3x3 array filled with 7
c = np.full((3, 3), 7)
print("\nFull array (3x3 filled with 7):\n", c)

# 4. New array of zeros with same shape and type as a given array
given_arr = np.array([[1, 2, 3], [4, 5, 6]])
d = np.zeros_like(given_arr)
print("\nZeros like given array:\n", d)

# 5. New array of ones with same shape and type as a given array
e = np.ones_like(given_arr)
print("\nOnes like given array:\n", e)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
f = np.array(new_list)
print("\nConverted numpy array:\n", f)


Empty 2x2 array:
 [[1.15387549e-318 0.00000000e+000]
 [1.19602393e+180 6.57318570e-310]]

All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
 [[0 0 0]
 [0 0 0]]

Ones like given array:
 [[1 1 1]
 [1 1 1]]

Converted numpy array:
 [1 2 3 4]


In [1]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array1 = np.arange(10, 50)
print("Array from 10 to 49:\n", array1)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix3x3)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of array:", mean_value)

# 5. Create a 10X10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Min value:", min_value, "Max value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # index starts from 0
print("\nZero array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.21825494 0.58113253 0.79537046 0.58404108 0.31887993 0.80416993
 0.46778624 0.2841325  0.23079211 0.72003039 0.81515844 0.99414316
 0.2227373  0.48494597 0.73624598 0.30509777 0.45178506 0.06082564
 0.77696618 0.08647639 0.57934524 0.18311879 0.58390996 0.43959946
 0.74391816 0.93709786 0.41469618 0.99725648 0.54408454 0.92088923]
Mean of array: 0.5427629304964448

10x10 Random Array:
 [[0.42688579 0.6548939  0.33563106 0.69164696 0.20132259 0.10217901
  0.81470469 0.54422026 0.57564377 0.79256443]
 [0.11910635 0.37794761 0.08675944 0.15315683 0.80821358 0.25915066
  0.61516566 0.90897607 0.27845773 0.24416299]
 [0.20031536 0.39050582 0.72797162 0.85118373 0.73448729 0.75621241
  0.92352983 0.53321985 0.8

In [2]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3. Multiply the array with an integer (e.g., 3)
mult_x = x * 3
print("\nx * 3:\n", mult_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\nx squared:\n", square_x)

# 5. Dot product
dot_vw = np.dot(v, w)        # dot product of vectors
dot_xv = np.dot(x, v)        # dot product of matrix and vector
dot_xy = np.dot(x, y)        # dot product of matrices

print("\nDot product v.w:", dot_vw)
print("Dot product x.v:\n", dot_xv)
print("Dot product x.y:\n", dot_xy)

# 6. Concatenate arrays
concat_row_xy = np.concatenate((x, y), axis=0)   # along rows
concat_col_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # along columns

print("\nConcatenate x and y along rows:\n", concat_row_xy)
print("Concatenate v and w along columns:\n", concat_col_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\nError concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.")


x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v:
 [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.


In [4]:
import numpy as np

# ----------------------
# Given Arrays
# ----------------------
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# ----------------------
# 1. Prove A × A⁻¹ = I
# ----------------------
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A × A⁻¹:\n", identity_check)

# ----------------------
# 2. Prove AB ≠ BA
# ----------------------
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB equal to BA?", np.array_equal(AB, BA))

# ----------------------
# 3. Prove (AB)ᵀ = BᵀAᵀ
# ----------------------
AB_transpose = (np.dot(A, B)).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("Are they equal?", np.array_equal(AB_transpose, BT_AT))

# ----------------------
# 4. Solve linear equations using inverse
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# ----------------------
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\n4. Solution using inverse [x, y, z]:", X)

# ----------------------
# Optional: Solve using np.linalg.solve (more efficient)
# ----------------------
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve [x, y, z]:", X_solve)


1. A × A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equal to BA? False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Are they equal? True

4. Solution using inverse [x, y, z]: [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z]: [ 2.  1. -2.]
